GET FILE='C:\EHA_SPSS\EX1.SAV'.

IF ID NE LAG(ID,1) ACDURA=0.
COMPUTE ACDURA=ACDURA+DURA.
IF ID NE LAG(ID,1) ORDER=0.
COMPUTE ORDER=ORDER+1.
LEAVE ACDURA ORDER.
LIST VAR=ID ORDER DURA ACDURA.

SELECT IF (ACDURA LE 1000).
LIST VAR=ID ORDER DURA ACDURA.

AGGREGATE OUTFILE=*
 /BREAK=ID
 /AVGDURA=MEAN(DURA)
 /MAXDURA=MAX(DURA)
 /MINDURA=MIN(DURA)
 /TOTDURA=SUM(DURA)
 /N=NU(DURA).
LIST VAR=ALL.
