INPUT PROGRAM.

DATA LIST FILE='C:\EHA_SPSS\EX2.DAT'
 /ID 1-3 SEX 5 AGE 7-8 RACE 10 EDU 12 NUMSPELL 14.
REPEATING DATA STARTS=16
 /OCCURS=NUMSPELL /LENGTH=7
 /DATA=DURA 1-4 EVENT 6.

END INPUT PROGRAM.

LIST VAR=ALL.
