TIME PROGRAM.
COMPUTE T_age=age+T_/365.
COMPUTE T_disease=DISEASE.
COMPUTE T_certi=CERTI. 
IF (DISEASET1>START & DISEASET2<END) & T_>DISEASET2 T_disease=1.
IF (CERT1>START & CERT1<END) & T_>CERT2 T_certi =1.
COXREG DUR
 /STATUS=EVENT(1)
 /CONTRAST (GENDER)=indicator
 /CONTRAST (T_certi)=indicator
 /CONTRAST (T_disease)=indicator
 /METHOD=ENTER T_age T_certi T_disease WAGE GENDER 
 /CRITERIA=PIN(.05) POUT(.10) ITERATE(20).